on:
  push:
    branches:
      - build-automation

jobs:
  build_and_push:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the repository
      - name: Check out the repository
        uses: actions/checkout@v4

      # Step 2: Debug repository structure to confirm paths
      - name: Debug directory structure
        run: |
          echo "Debugging directory structure..."
          ls -R
          echo "Checking for package.json..."
          if [ -f bulletin-board-app/package.json ]; then
            echo "package.json found at bulletin-board-app/package.json"
            cat bulletin-board-app/package.json
          else
            echo "package.json NOT found in bulletin-board-app"
            exit 1
          fi

      # Step 3: Install dependencies
      - name: Install dependencies
        run: |
          echo "Running npm install in bulletin-board-app..."
          npm install --prefix bulletin-board-app

      # Step 4: Log in to Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v4
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Step 5: Build and push Docker image
      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: bulletin-board-app
          file: bulletin-board-app/Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/itm350-${{ secrets.DOCKER_USERNAME }}-bb:1.0
