on:
  push:
    branches:
      - build-automation

jobs:
  if_pushed:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the repository
      - name: Check out the repo
        uses: actions/checkout@v4

      # Step 2: Debug the directory structure to confirm paths
      - name: Debug repository structure
        run: |
          ls -R

      # Step 3: Install dependencies
      - name: Install dependencies
        run: |
          npm install --prefix bulletin-board-app

      # Step 4: Log in to Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v4
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Step 5: Build and push Docker image
      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: bulletin-board-app
          file: bulletin-board-app/Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/itm350-${{ secrets.DOCKER_USERNAME }}-bb:1.0
