on:
  push:
    branches: 
      - main
env:
  REPO_NAME: tylers5x/itm350-tylers5x-bb

jobs:
  if_pushed:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo Code was pushed to the main branch

      - name: Check out the repo
        uses: actions/checkout@v2

      - name: Install dependencies
      - run: |
          npm install --prefix bb/node-bulletin-board/bulletin-board-app
      
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: ${{ env.REPO_NAME }}
          tags: |
            type=sha  
      
      - name: Build and push Docker image
        uses: docker/build-push-action@v3
        with:
          context: .
          file: ./Dockerfile
          push: true
          tag_with_sha: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
